export const mockCouponTopData = [
  {
    couponLalaPddata: {
      url: '',
      productName: '個人清潔指定品滿500元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '特惠<br>神券',
      discountPrice: 'C068050',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 100,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
  {
    couponLalaPddata: {
      url: '',
      productName: '電動工具指定品滿30000元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '特惠<br>神券',
      discountPrice: 'C067556',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 3000,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
];

export const mockCouponBotData = [
  {
    couponLalaPddata: {
      url: '',
      productName: '康寧指定品滿1499元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '好康券',
      discountPrice: 'C067866',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 120,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
  {
    couponLalaPddata: {
      url: '',
      productName: '通訊殼貼/配件滿1500元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '好康券',
      discountPrice: 'C068043',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 120,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
  {
    couponLalaPddata: {
      url: '',
      productName: '食品/日用指定品滿1000元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '好康券',
      discountPrice: 'C067562',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 120,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
  {
    couponLalaPddata: {
      url: '',
      productName: 'Marshall指定品滿10000元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '好康券',
      discountPrice: 'C068206',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 1500,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
  {
    couponLalaPddata: {
      url: '',
      productName: '白蘭氏指定單品滿3000元',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '好康券',
      discountPrice: 'C068111',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 300,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
  {
    couponLalaPddata: {
      url: '',
      productName: '健身/水陸運動滿12121',
      productTitle: '商品優惠訊息 商品優惠訊息',
      marketPrice: '好康券',
      discountPrice: 'C068114',
      imgSrc: '',
      imgTitle: '圖片說明',
    }, // 行銷後台上稿資料
    couponActivityData: {
      Id: null,
      Name: '部份商品適用',
      Status: null,
      CouponSendStatus: null,
      UseStartDate: '2025/12/01 00:00:00',
      UseEndDate: '2026/01/31 23:59:59',
      SendAmtMode: 'Amount',
      SendAmt: 1212,
      UseAmtLimit: null,
      UseFieldMode: null,
      UseField: null,
      Mac: null,
      ManuelUseDesc: null,
      Source: null,
      isUseLimit: null,
      isStage: null,
      isPublic: null,
      SubUseFieldMode: null,
      SubUseField: null,
      ItemNum: null,
      UseDevice: null,
      isSerial: null,
      ManualSerialId: null,
      CouponId: null,
      SendType: null,
      UseType: null,
      UseLimitMode: null,
      UseLimit: null,
    }, // 折價券 api 資料
    couponGot: true,
    couponClickState: false,
  },
];
